language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
addons:
  apt:
    packages:
      - libsecret-1-dev
script:
  - npm run test
after_success:
  - npm run report-coverage
